# Generated by Django 5.0.1 on 2024-04-29 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='email_address',
            new_name='EmailAddress',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='phone_number',
            new_name='PhoneNumber',
        ),
    ]
