# Generated by Django 5.0.1 on 2024-04-29 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0002_rename_email_address_signup_emailaddress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='EmailAddress',
            new_name='email_address',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='PhoneNumber',
            new_name='phone_number',
        ),
    ]
