# Generated by Django 5.0.1 on 2024-04-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0003_rename_emailaddress_signup_email_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='name',
            new_name='full_name',
        ),
    ]
