# Generated by Django 5.0.1 on 2024-04-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_rename_name_signup_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='full_name',
            new_name='name',
        ),
    ]
