# Generated by Django 5.0.1 on 2024-04-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0005_rename_full_name_signup_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='email_address',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
